// <auto-generated />
using System;
using DAL.Module;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240224190914_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("DAL.Model.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardCategory = 1,
                            CardType = 14,
                            Image = "AC.png",
                            Name = "CLUBS A"
                        },
                        new
                        {
                            Id = 2,
                            CardCategory = 1,
                            CardType = 2,
                            Image = "2C.png",
                            Name = "CLUBS 2"
                        },
                        new
                        {
                            Id = 3,
                            CardCategory = 1,
                            CardType = 3,
                            Image = "3C.png",
                            Name = "CLUBS 3"
                        },
                        new
                        {
                            Id = 4,
                            CardCategory = 1,
                            CardType = 4,
                            Image = "4C.png",
                            Name = "CLUBS 4"
                        },
                        new
                        {
                            Id = 5,
                            CardCategory = 1,
                            CardType = 5,
                            Image = "5C.png",
                            Name = "CLUBS 5"
                        },
                        new
                        {
                            Id = 6,
                            CardCategory = 1,
                            CardType = 6,
                            Image = "6C.png",
                            Name = "CLUBS 6"
                        },
                        new
                        {
                            Id = 7,
                            CardCategory = 1,
                            CardType = 7,
                            Image = "7C.png",
                            Name = "CLUBS 7"
                        },
                        new
                        {
                            Id = 8,
                            CardCategory = 1,
                            CardType = 8,
                            Image = "8C.png",
                            Name = "CLUBS 8"
                        },
                        new
                        {
                            Id = 9,
                            CardCategory = 1,
                            CardType = 9,
                            Image = "9C.png",
                            Name = "CLUBS 9"
                        },
                        new
                        {
                            Id = 10,
                            CardCategory = 1,
                            CardType = 10,
                            Image = "10C.png",
                            Name = "CLUBS 10"
                        },
                        new
                        {
                            Id = 11,
                            CardCategory = 1,
                            CardType = 11,
                            Image = "JC.png",
                            Name = "CLUBS J"
                        },
                        new
                        {
                            Id = 12,
                            CardCategory = 1,
                            CardType = 13,
                            Image = "QC.png",
                            Name = "CLUBS Q"
                        },
                        new
                        {
                            Id = 13,
                            CardCategory = 1,
                            CardType = 12,
                            Image = "KC.png",
                            Name = "CLUBS K"
                        },
                        new
                        {
                            Id = 14,
                            CardCategory = 2,
                            CardType = 14,
                            Image = "AD.png",
                            Name = "DIAMONDS A"
                        },
                        new
                        {
                            Id = 15,
                            CardCategory = 2,
                            CardType = 2,
                            Image = "2D.png",
                            Name = "DIAMONDS 2"
                        },
                        new
                        {
                            Id = 16,
                            CardCategory = 2,
                            CardType = 3,
                            Image = "3D.png",
                            Name = "DIAMONDS 3"
                        },
                        new
                        {
                            Id = 17,
                            CardCategory = 2,
                            CardType = 4,
                            Image = "4D.png",
                            Name = "DIAMONDS 4"
                        },
                        new
                        {
                            Id = 18,
                            CardCategory = 2,
                            CardType = 5,
                            Image = "5D.png",
                            Name = "DIAMONDS 5"
                        },
                        new
                        {
                            Id = 19,
                            CardCategory = 2,
                            CardType = 6,
                            Image = "6D.png",
                            Name = "DIAMONDS 6"
                        },
                        new
                        {
                            Id = 20,
                            CardCategory = 2,
                            CardType = 7,
                            Image = "7D.png",
                            Name = "DIAMONDS 7"
                        },
                        new
                        {
                            Id = 21,
                            CardCategory = 2,
                            CardType = 8,
                            Image = "8D.png",
                            Name = "DIAMONDS 8"
                        },
                        new
                        {
                            Id = 22,
                            CardCategory = 2,
                            CardType = 9,
                            Image = "9D.png",
                            Name = "DIAMONDS 9"
                        },
                        new
                        {
                            Id = 23,
                            CardCategory = 2,
                            CardType = 10,
                            Image = "10D.png",
                            Name = "DIAMONDS 10"
                        },
                        new
                        {
                            Id = 24,
                            CardCategory = 2,
                            CardType = 11,
                            Image = "JD.png",
                            Name = "DIAMONDS J"
                        },
                        new
                        {
                            Id = 25,
                            CardCategory = 2,
                            CardType = 13,
                            Image = "QD.png",
                            Name = "DIAMONDS Q"
                        },
                        new
                        {
                            Id = 26,
                            CardCategory = 2,
                            CardType = 12,
                            Image = "KD.png",
                            Name = "DIAMONDS K"
                        },
                        new
                        {
                            Id = 27,
                            CardCategory = 3,
                            CardType = 14,
                            Image = "AH.png",
                            Name = "HEARTS A"
                        },
                        new
                        {
                            Id = 28,
                            CardCategory = 3,
                            CardType = 2,
                            Image = "2H.png",
                            Name = "HEARTS 2"
                        },
                        new
                        {
                            Id = 29,
                            CardCategory = 3,
                            CardType = 3,
                            Image = "3H.png",
                            Name = "HEARTS 3"
                        },
                        new
                        {
                            Id = 30,
                            CardCategory = 3,
                            CardType = 4,
                            Image = "4H.png",
                            Name = "HEARTS 4"
                        },
                        new
                        {
                            Id = 31,
                            CardCategory = 3,
                            CardType = 5,
                            Image = "5H.png",
                            Name = "HEARTS 5"
                        },
                        new
                        {
                            Id = 32,
                            CardCategory = 3,
                            CardType = 6,
                            Image = "6H.png",
                            Name = "HEARTS 6"
                        },
                        new
                        {
                            Id = 33,
                            CardCategory = 3,
                            CardType = 7,
                            Image = "7H.png",
                            Name = "HEARTS 7"
                        },
                        new
                        {
                            Id = 34,
                            CardCategory = 3,
                            CardType = 8,
                            Image = "8H.png",
                            Name = "HEARTS 8"
                        },
                        new
                        {
                            Id = 35,
                            CardCategory = 3,
                            CardType = 9,
                            Image = "9H.png",
                            Name = "HEARTS 9"
                        },
                        new
                        {
                            Id = 36,
                            CardCategory = 3,
                            CardType = 10,
                            Image = "10H.png",
                            Name = "HEARTS 10"
                        },
                        new
                        {
                            Id = 37,
                            CardCategory = 3,
                            CardType = 11,
                            Image = "JH.png",
                            Name = "HEARTS J"
                        },
                        new
                        {
                            Id = 38,
                            CardCategory = 3,
                            CardType = 13,
                            Image = "QH.png",
                            Name = "HEARTS Q"
                        },
                        new
                        {
                            Id = 39,
                            CardCategory = 3,
                            CardType = 12,
                            Image = "KH.png",
                            Name = "HEARTS K"
                        },
                        new
                        {
                            Id = 40,
                            CardCategory = 4,
                            CardType = 14,
                            Image = "AS.png",
                            Name = "SPADES A"
                        },
                        new
                        {
                            Id = 41,
                            CardCategory = 4,
                            CardType = 2,
                            Image = "2S.png",
                            Name = "SPADES 2"
                        },
                        new
                        {
                            Id = 42,
                            CardCategory = 4,
                            CardType = 3,
                            Image = "3S.png",
                            Name = "SPADES 3"
                        },
                        new
                        {
                            Id = 43,
                            CardCategory = 4,
                            CardType = 4,
                            Image = "4S.png",
                            Name = "SPADES 4"
                        },
                        new
                        {
                            Id = 44,
                            CardCategory = 4,
                            CardType = 5,
                            Image = "5S.png",
                            Name = "SPADES 5"
                        },
                        new
                        {
                            Id = 45,
                            CardCategory = 4,
                            CardType = 6,
                            Image = "6S.png",
                            Name = "SPADES 6"
                        },
                        new
                        {
                            Id = 46,
                            CardCategory = 4,
                            CardType = 7,
                            Image = "7S.png",
                            Name = "SPADES 7"
                        },
                        new
                        {
                            Id = 47,
                            CardCategory = 4,
                            CardType = 8,
                            Image = "8S.png",
                            Name = "SPADES 8"
                        },
                        new
                        {
                            Id = 48,
                            CardCategory = 4,
                            CardType = 9,
                            Image = "9S.png",
                            Name = "SPADES 9"
                        },
                        new
                        {
                            Id = 49,
                            CardCategory = 4,
                            CardType = 10,
                            Image = "10S.png",
                            Name = "SPADES 10"
                        },
                        new
                        {
                            Id = 50,
                            CardCategory = 4,
                            CardType = 11,
                            Image = "JS.png",
                            Name = "SPADES J"
                        },
                        new
                        {
                            Id = 51,
                            CardCategory = 4,
                            CardType = 13,
                            Image = "QS.png",
                            Name = "SPADES Q"
                        },
                        new
                        {
                            Id = 52,
                            CardCategory = 4,
                            CardType = 12,
                            Image = "KS.png",
                            Name = "SPADES K"
                        });
                });

            modelBuilder.Entity("DAL.Model.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("game");
                });

            modelBuilder.Entity("DAL.Model.GameCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlipedState")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlippedOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlippedPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsMatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("FlippedPlayerId");

                    b.HasIndex("GameId");

                    b.ToTable("gameCard");
                });

            modelBuilder.Entity("DAL.Model.GamePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("gamePlayer");
                });

            modelBuilder.Entity("DAL.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Player 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Player 2"
                        });
                });

            modelBuilder.Entity("DAL.Model.GameCard", b =>
                {
                    b.HasOne("DAL.Model.Card", "Card")
                        .WithMany("GameCard")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Model.Player", "FlippedPlayer")
                        .WithMany("GameCard")
                        .HasForeignKey("FlippedPlayerId");

                    b.HasOne("DAL.Model.Game", "Game")
                        .WithMany("GameCard")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("FlippedPlayer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DAL.Model.GamePlayer", b =>
                {
                    b.HasOne("DAL.Model.Game", "Game")
                        .WithMany("GamePlayer")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Model.Player", "Player")
                        .WithMany("GamePlayer")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DAL.Model.Card", b =>
                {
                    b.Navigation("GameCard");
                });

            modelBuilder.Entity("DAL.Model.Game", b =>
                {
                    b.Navigation("GameCard");

                    b.Navigation("GamePlayer");
                });

            modelBuilder.Entity("DAL.Model.Player", b =>
                {
                    b.Navigation("GameCard");

                    b.Navigation("GamePlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
